version: '3'
services:
    producer:
        env_file: 
        - .env
        build:
            context: .
            dockerfile: .Dockerfile
        depends_on:
            - s3_consumer
            - elasticsearch_consumer
            - notification_consumer
        command: 
            - python3 
            - -u 
            - producer/producer.py
    s3_consumer:
        env_file: 
        - .env
        build:
            context: .
            dockerfile: .Dockerfile
        command: 
            - python3
            - -u
            - consumers/s3_consumer.py
    elasticsearch_consumer:
        env_file: 
        - .env
        build:
            context: .
            dockerfile: .Dockerfile
        command: 
            - python3
            - -u
            - consumers/elasticsearch_consumer.py
    notification_consumer:
        env_file: 
        - .env
        build:
            context: .
            dockerfile: .Dockerfile
        command: 
            - python3
            - -u
            - consumers/notification_consumer.py
  